### ISSUE TITLE
running DEMO1 produces errors

### ISSUE THREAD

**Issue by GoogleCodeExporter** [iousprafa/nctoolbox#34]
```
When I run demo1, from nctoolbox-20120109.zip, I get errors. Since this is the 
first demo people might run (to test if their installation is working, for 
example, we should have a demo that gives no errors). If these errors are 
because someone messed with the file, we should take a copy of this file and 
put it somewhere under our control (e.g. http://geoport.whoi.edu) and serve it 
there.

% STARTING DEMO1 ----------------------------------------------------------
% Basic usage of ncdataset
%% ---- Open your data
% Can be NetCDF, NetCDF on webserver, or OpenDAP
ds = 
ncdataset('http://dods.mbari.org/cgi-bin/nph-nc/data/ssdsdata/deployments/m1/200
810/OS_M1_20081008_TS.nc');
yyerror: DAS line 139 near |program|; syntax error, unexpected SCAN_PROG, 
expecting '{'java.lang.Exception
    at opendap.dap.parsers.Daplex.yyerror(Daplex.java:496)
    at opendap.dap.parsers.DapParser.yyerror(DapParser.java:204)
    at opendap.dap.parsers.DapParser.parse(DapParser.java:1438)
    at opendap.dap.parsers.DapParser.parse(DapParser.java:1979)
    at opendap.dap.parsers.Dapparse.dapparse(Dapparse.java:120)
    at opendap.dap.parsers.Dapparse.dasparse(Dapparse.java:136)
    at opendap.dap.DAS.parse(DAS.java:137)
    at opendap.dap.DConnect2$DASCommand.process(DConnect2.java:473)
    at opendap.dap.DConnect2.openConnection(DConnect2.java:313)
    at opendap.dap.DConnect2.getDAS(DConnect2.java:460)
    at ucar.nc2.dods.DODSNetcdfFile.<init>(DODSNetcdfFile.java:220)
    at ucar.nc2.dataset.NetcdfDataset.acquireDODS(NetcdfDataset.java:809)
    at ucar.nc2.dataset.NetcdfDataset.openOrAcquireFile(NetcdfDataset.java:679)
    at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:424)
    at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:407)
    at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:392)
    at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:379)
Illegal attribute
opendap.dap.parsers.ParseException: context: ^
    at opendap.dap.parsers.Dapparse.dap_parse_error(Dapparse.java:512)
    at opendap.dap.parsers.Dapparse.daperror(Dapparse.java:499)
    at opendap.dap.parsers.DapParser.yyaction(DapParser.java:746)
    at opendap.dap.parsers.DapParser.parse(DapParser.java:1426)
    at opendap.dap.parsers.DapParser.parse(DapParser.java:1979)
    at opendap.dap.parsers.Dapparse.dapparse(Dapparse.java:120)
    at opendap.dap.parsers.Dapparse.dasparse(Dapparse.java:136)
    at opendap.dap.DAS.parse(DAS.java:137)
    at opendap.dap.DConnect2$DASCommand.process(DConnect2.java:473)
    at opendap.dap.DConnect2.openConnection(DConnect2.java:313)
    at opendap.dap.DConnect2.getDAS(DConnect2.java:460)
    at ucar.nc2.dods.DODSNetcdfFile.<init>(DODSNetcdfFile.java:220)
    at ucar.nc2.dataset.NetcdfDataset.acquireDODS(NetcdfDataset.java:809)
    at ucar.nc2.dataset.NetcdfDataset.openOrAcquireFile(NetcdfDataset.java:679)
    at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:424)
    at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:407)
    at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:392)
    at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:379)


```

Original issue reported on code.google.com by `rsignell` on 30 Jan 2012 at 12:44

**Comment by GoogleCodeExporter** [comment]
```
Okay, actually, I decided just to fix all the demos.  Just made the commit and 
pushed to server if you want to test.

```

Original comment by `rsignell` on 30 Jan 2012 at 4:07
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
Just a note that the original error seemed to be due to a bug in the opendap 
libraries. I updated all nctoolboxes Java dependencies and this bug goes away. 
See nctoolbox-20130228
```

Original comment by `bschlin...@gmail.com` on 28 Feb 2013 at 8:20
