### ISSUE TITLE
Add proxy support for nctoolbox

### ISSUE THREAD

**Issue by GoogleCodeExporter** [iousprafa/nctoolbox#4]
```
From phubbard: 
"I need to configure nctoolbox to use my shiny new http proxy. Any idea of 
where to start? I was hoping it'd use the .dodsrc, but it doesn't seem to."

It looks like it should be possible. See emails at 
https://www.unidata.ucar.edu/support/help/MailArchives/netcdf/msg04150.
html and 
https://www.unidata.ucar.edu/support/help/MailArchives/netcdf/msg03242.
html

Further details are on the OOI CI wiki at 
http://www.oceanobservatories.org/spaces/display/CIDev/MATLAB,+DataExc
hange+and+http+proxies
```

Original issue reported on code.google.com by `bschlin...@gmail.com` on 6 Feb 2010 at 8:21

**Comment by GoogleCodeExporter** [comment]
```
It looks like the key is to configure the proxy in Apache common-http which is 
used by 
DConnect2.java in opendap. I decompiled DConnect2 (couldn't find the source) 
and 
have attached it for reference.
```

Original comment by `bschlin...@gmail.com` on 6 Feb 2010 at 8:24

Attachments:
- [DConnect2.java](https://storage.googleapis.com/google-code-attachments/nctoolbox/issue-4/comment-1/DConnect2.java)

**Comment by GoogleCodeExporter** [comment]
```
Here's the java code snippet that is supposed to configure the proxy from the 
email 
at https://www.unidata.ucar.edu/support/help/MailArchives/netcdf/msg03242.
html :

System.setProperty("http.proxyHost", "myproxyhost.com");
System.setProperty("http.proxyPort", "8080");
Authenticator.setDefault(new Authenticator() {
  public PasswordAuthentication getPasswordAuthentication() {
    return new PasswordAuthentication("myusername", mypassword".toCharArray());
  }
});
```

Original comment by `bschlin...@gmail.com` on 6 Feb 2010 at 8:35

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
Fetched commons-httpclient source code with the following: 
svn checkout http://svn.apache.org/repos/asf/httpcomponents/oac.hc3x/trunk 
commons-httpclient

```

Original comment by `bschlin...@gmail.com` on 6 Feb 2010 at 8:37

**Comment by GoogleCodeExporter** [comment]
```
Here's some references for proxies:

Official Oracle JVM settings are at 
http://java.sun.com/javase/6/docs/technotes/guides/net/properties.html (Same as 
in comments above. Need to see if they work with commons-httpclient used by 
opendap,jar)

Essentially a repeat of the above at 
http://info4tech.wordpress.com/2007/05/04/java-http-proxy-settings/

and here's a link to the commons wiki which is short, sweet and almost, but not 
really 
helpful 
http://wiki.apache.org/HttpComponents/FrequentlyAskedApplicationDesignQuestion
s

```

Original comment by `bschlin...@gmail.com` on 7 Feb 2010 at 9:21

**Comment by GoogleCodeExporter** [comment]
```
Here's the essence of the above links for setting proxies in commons-httpclient:

// Read/get proxyhost, port from wherever. If you want to use the 
// System properties then you have to read them, they are NOT the
// defaults for the client.
HttpClient client = new HttpClient();
client.getHostConfiguration().setProxy(proxyHost, port);
```

Original comment by `bschlin...@gmail.com` on 7 Feb 2010 at 9:25

**Comment by GoogleCodeExporter** [comment]
```
I think I found the solution. There's the static method 
NetcdfDataset.setHttpClient(HttpClient hc) which "Set the HttpClient object - 
so that a 
single, shared instance is used within the application." Perfect!

For now, I'll modify ncdataset to read properties from ~/.dodsrc, if it exists, 
and use 
that info to configure the proxy settings.
```

Original comment by `bschlin...@gmail.com` on 7 Feb 2010 at 9:58

**Comment by GoogleCodeExporter** [comment]
```
Tried the following to test proxy:
>>  httpClient = org.apache.commons.httpclient.HttpClient()
>>  httpClient.getHostConfiguration().setProxy('proxy.hostname.edu', 9001)
>>  ucar.nc2.dataset.NetcdfDataset.setHttpClient(httpClient)

Tested against non-DX all-pass proxy with the following:

WORKED

>> ds = 
ncdataset('http://thredds1.pfeg.noaa.gov/thredds/dodsC/satellite/MB/chla/mday')

>> ds = 
ncdataset('http://www.esrl.noaa.gov/psd/thredds/dodsC/Datasets/ncep.reanalysis/s
urface_gauss/vwnd.10m.gauss.2009.
nc')

>> ds = 
cfdataset('http://blackburn.whoi.edu:8081/thredds/dodsC/coawst/fmrc/coawst_2_bes
t.ncd')


BOMBED

ds = ncdataset('http://dods.mbari.org/cgi-bin/nph-
nc/data/ssdsdata/deployments/m1/200810/OS_M1_20081008_TS.nc');
??? Error using ==> ncdataset>ncdataset.ncdataset at 89
Failed to open 
http://dods.mbari.org/cgi-bin/nph-nc/data/ssdsdata/deployments/m1/200810/OS_M1_2
0081008_TS.nc

Error in ==> demo1 at 6
ds = ncdataset('http://dods.mbari.org/cgi-bin/nph-
nc/data/ssdsdata/deployments/m1/200810/OS_M1_20081008_TS.nc');

Caused by:
    Java exception occurred:
    java.io.IOException:
    http://dods.mbari.org/cgi-bin/nph-nc/data/ssdsdata/deployments/m1/200810/OS_M1_20081008_TS.nc HTTP/1.0 
400 DODS
    server filter program not found.
        at ucar.unidata.io.http.HTTPRandomAccessFile.doConnect(HTTPRandomAccessFile.java:181)
        at ucar.unidata.io.http.HTTPRandomAccessFile.<init>(HTTPRandomAccessFile.java:114)
        at ucar.unidata.io.http.HTTPRandomAccessFile.<init>(HTTPRandomAccessFile.java:95)
        at ucar.nc2.NetcdfFile.getRaf(NetcdfFile.java:486)
        at ucar.nc2.NetcdfFile.open(NetcdfFile.java:392)
        at ucar.nc2.dataset.NetcdfDataset.openOrAcquireFile(NetcdfDataset.java:688)
        at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:434)
        at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:417)
        at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:402)
        at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:389)


```

Original comment by `bschlin...@gmail.com` on 16 Feb 2010 at 10:11

**Comment by GoogleCodeExporter** [comment]
```
Here's a DAPPER URL that worked fine:
>> ds = ncdataset('http://dapper.pmel.noaa.gov/dapper/epic/wcoast_prof_ctd.cdp')
```

Original comment by `bschlin...@gmail.com` on 16 Feb 2010 at 10:24

**Comment by GoogleCodeExporter** [comment]
```
Here's another OpenDAP URL that worked fine:
>> ds = ncdataset('http://www.marine.csiro.au/dods/nph-dods/dods-
data/climatology-netcdf/terrainbase.nc')

Looks like MBARI may be running an older version of DODS that's causing some 
trouble 
with proxies.
```

Original comment by `bschlin...@gmail.com` on 16 Feb 2010 at 10:28

**Comment by GoogleCodeExporter** [comment]
```
Created setproxy.m at 
http://code.google.com/p/nctoolbox/source/browse/cdm/setproxy.m 

I'm passing this on to phubbard for testing.
```

Original comment by `bschlin...@gmail.com` on 17 Feb 2010 at 4:53

Attachments:
- [setproxy.m](https://storage.googleapis.com/google-code-attachments/nctoolbox/issue-4/comment-11/setproxy.m)

**Comment by GoogleCodeExporter** [comment]
```
Also tried the following in Matlab with no problems. (this HTTP URL is known to 
redirect 
to a DODS URL):

>> setproxy('myproxy.name.edu', 9001)
>>  ds = 
ncdataset('http://www.esrl.noaa.gov/psd/thredds/dodsC/Datasets/ncep.marine/sst.m
e
an.nc')
```

Original comment by `bschlin...@gmail.com` on 17 Feb 2010 at 4:55

**Comment by GoogleCodeExporter** [comment]
```
Interesting. Looks like 'setproxy' only handles URL's that start with HTTP not 
DODS. 
For example:
>> setproxy('bogus.url.com', 9001)
>>  ds = 
ncdataset('dods://www.esrl.noaa.gov/psd/thredds/dodsC/Datasets/ncep.marine/sst.
mean.nc')

Works fine (Note the dods url) although the proxy is bogus. But trying to 
connect 
with an HTTP URL:
>> ds = 
ncdataset('http://www.esrl.noaa.gov/psd/thredds/dodsC/Datasets/ncep.marine/sst.
mean.nc')
??? Error using ==> ncdataset>ncdataset.ncdataset at 89
Failed to open 
http://www.esrl.noaa.gov/psd/thredds/dodsC/Datasets/ncep.marine/sst.mean.nc

Caused by:
    Java exception occurred:
    java.net.UnknownHostException: bogus.url.com
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:177)
        ...



```

Original comment by `bschlin...@gmail.com` on 17 Feb 2010 at 5:05

**Comment by GoogleCodeExporter** [comment]
```
From phubbard:

"We're testing now, looks like we may have to use libdap. nctoolbox is using 
HEAD 
instead of GET methods, and I didn't implement HEAD in DX. The DAP 2 spec I 
worked 
from only specifies GET, drat."
```

Original comment by `bschlin...@gmail.com` on 17 Feb 2010 at 6:29

**Comment by GoogleCodeExporter** [comment]
```
References for HTTP GET and DAP protocol:

http://www.esdswg.org/spg/rfc/ese-rfc-004
http://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html
```

Original comment by `bschlin...@gmail.com` on 17 Feb 2010 at 6:57

**Comment by GoogleCodeExporter** [comment]
```
I sent the following note to opendap and netcdf-java mailing lists:

"Is it possible to get the source code for opendap-java? I can't seem to find 
it. I'm 
having some issues with configuring a proxy for opendap when using netcdf-java 
and was hoping the source would help me get to the bottom of it. 

Specifically, when I open a opendap url via netcd-java using: 
ucar.nc2.dataset.NetcdfDataset.openDataset(url); I think somewhere along the 
call 
chain it's using opendap.dap.DConnect2. (Please someone correct me if I'm 
wrong!) 
The only HTTP method call in DConnect2 is GET (e.g. 
org.apache.commons.httpclient.methods.GetMethod). However it appears to be 
making a HEAD calls too even though HeadMethod is not called directly. Also, is 
HTTP HEAD required for the DAP 2 spec?

Also, is anyone interested in updating opendap-java to use an updated version 
of 
Apace HttpClient  in opendap-java? It's currently using 3.x but theres a 4.x 
branch at 
http://hc.apache.org/ with the admonition of:

'Commons HttpClient 3.x codeline is nearing the end of life. All users of 
Commons 
HttpClient 3.x are strongly encouraged to upgrade to HttpClient 4.0.'"



The response was from Nathan Potter:

"The Java implmentation of the DAP is not under active development. It is 
available 
through our subversion server here:

  http://scm.opendap.org/svn/trunk/Java-OPeNDAP/

It is available for public checkout:

  svn co http://scm.opendap.org/svn/trunk/Java-OPeNDAP/

If in your endeavors you find that you can improve it we would be happy to look 
at 
including your changes/updates."

```

Original comment by `bschlin...@gmail.com` on 18 Feb 2010 at 5:16

**Comment by GoogleCodeExporter** [comment]
```
I also asked Paul to confirm that HTTP HEAD requests were being sent. He said:

HEAD for sure - 

2010-02-17 19:07:22+0000 [-] [proxyng] 2010-02-17 19:07:22+0000 
[ProxyClient, client] 137.110.111.157 - - [17/Feb/2010:19:07:21 +0000] "HEAD 
http://amoeba.ucsd.edu:8001/coads.nc.dds HTTP/1.1" 200 - "-" "Jakarta 
Commons-HttpClient/3.1"

```

Original comment by `bschlin...@gmail.com` on 18 Feb 2010 at 5:18

**Comment by GoogleCodeExporter** [comment]
```
Attached a groovy script for displaying headers from a given URL.
```

Original comment by `bschlin...@gmail.com` on 19 Feb 2010 at 8:08

Attachments:
- [urlheaders.groovy](https://storage.googleapis.com/google-code-attachments/nctoolbox/issue-4/comment-18/urlheaders.groovy)

**Comment by GoogleCodeExporter** [comment]
```
For grins, I modified script to dump the HTTP headers (The script allows you to 
specify a proxy to see the effects on the header)

**** urlheaders.groovy  http://amoeba.ucsd.edu:8001/coads.nc.dds ****
HTTP/1.0 200 OK
Date: Fri, 19 Feb 2010 23:11:22 GMT
Content-type: text/plain
Content-description: dods_dds
Connection: close
Server: PasteWSGIServer/0.5 Python/2.6.2
XDODS-Server: dods/2.0

**** urlheaders.groovy  http://amoeba.ucsd.edu:8001/coads.nc.dds 
amoeba.ucsd.edu:9001 ****
HTTP/1.1 200 OK
Xdods-Server: dods/2.0
Content-Description: dods_dds
Transfer-Encoding: chunked
Date: Fri, 19 Feb 2010 23:11:16 GMT
Connection: close
Content-Type: text/plain
Server: PasteWSGIServer/0.5 Python/2.6.2


**** urlheaders.groovy  
http://www.esrl.noaa.gov/psd/thredds/dodsC/Datasets/ncep.marine/sst.mean.nc 
****
HTTP/1.1 400 Bad Request
Content-Description: dods-error
Date: Fri, 19 Feb 2010 23:13:00 GMT
Vary: Accept-Encoding
Transfer-Encoding: chunked
Content-Type: text/plain; charset=ISO-8859-1
Connection: close

**** urlheaders.groovy  
http://www.esrl.noaa.gov/psd/thredds/dodsC/Datasets/ncep.marine/sst.mean.nc 
amoeba.ucsd.edu:9001 ***
HTTP/1.1 400 Bad Request
Content-Description: dods-error
Transfer-Encoding: chunked
Date: Fri, 19 Feb 2010 23:13:18 GMT
Vary: Accept-Encoding
Connection: close
Content-Type: text/plain; charset=ISO-8859-1

I can use this to test agains OOI's DX server at some point.
```

Original comment by `bschlin...@gmail.com` on 19 Feb 2010 at 11:23

Attachments:
- [urlheaders.groovy](https://storage.googleapis.com/google-code-attachments/nctoolbox/issue-4/comment-19/urlheaders.groovy)

**Comment by GoogleCodeExporter** [comment]
```
Closing this for now. The NetCDF-Java guys may be switch from HttpClient 3.x to 
HttpClient 4.x. No point in 
putting more effort into this until that's completed.
```

Original comment by `bschlin...@gmail.com` on 1 Apr 2010 at 11:33
- Changed state: **Fixed**
